backend:
  name: git-gateway
  branch: master

media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "config"
    label: "Configurações"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Configuração do site"
        file: "config.json"
        description: "Configurações gerais do site"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Não insira a barra final do URL"
          - label: "Título"
            name: "site_title"
            widget: "string"
          - label: "Descrição"
            name: "site_description"
            widget: "string"
          - label: "Palavras-chave"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: "Palavra-chave"
              name: keyword
              widget: "string"
          - label: "Qtd Posts por página"
            name: "posts_per_page"
            widget: "number"
            default: 5
            value_type: "int"
            min: 1
            max: 20
          - label: "Twitter"
            name: "twitter_account"
            widget: "string"
          - label: "Instagram"
            name: "instagram_account"
            widget: "string"
          - label: "LinkedIn"
            name: "linkedin_account"
            widget: "string"
          - label: "E-mail"
            name: "mail_account"
            widget: "string"
          - label: "Telefone"
            name: "phone_number"
            widget: "string"
          - label: "Cor primária"
            name: "color_primary"
            widget: "string"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Autores"
        file: "meta/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Autores
            label_singular: "Autor"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                required: true
                pattern:
                  [
                    "^[a-z0-9]+(?:-[a-z0-9]+)*$",
                    "Um slug não pode ter espaços ou caracteres especiais",
                  ]
                widget: "string"
                hint: "A parte de um URL identifica o autor"
              - label: "Nome"
                name: "name"
                widget: "string"
              - label: "Introdução"
                name: "introduction"
                widget: "text"
      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                required: true
                pattern:
                  [
                    "^[a-z0-9]+(?:-[a-z0-9]+)*$",
                    "Um slug não pode ter espaços ou caracteres especiais",
                  ]
                widget: "string"
                hint: "A parte de um URL identifica a tag"
              - label: "Nome"
                name: "name"
                widget: "string"
                hint: "Nome da tag para exibição no site"

  - name: "posts"
    label: "Postagens"
    folder: "src/pages/posts"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Slug"
        name: "slug"
        required: true
        pattern:
          [
            "^[a-z0-9]+(?:-[a-z0-9]+)*$",
            "Um slug não pode ter espaços ou caracteres especiais",
          ]
        widget: "string"
      - label: "Título"
        name: "title"
        widget: "string"
      - label: "Data Publicação"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: Autor
        name: "author"
        widget: relation
        collection: "meta"
        file: "authors"
        searchFields:
          - "authors.*.name"
        displayFields:
          - "authors.*.name"
        valueField: "authors.*.slug"
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: "Texto"
        name: "body"
        widget: "markdown"
